# -*- coding: utf-8 -*-
"""djikstra's

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1DysNelGjkZ1z6iYWNe8ubBZ6YO0u2t
"""

from Project3.config import STARTING_POSITION_NUMBER
import pandas as pd
import numpy as np
import heapq
from scipy.interpolate import CubicSpline


def get_grid_data(csv_path):

    df = pd.read_csv(csv_path, header=None)

    return np.array(df)


def get_padded_grid(grid, radius):
    padded_grid = np.copy(grid)
    obstacles = np.where(grid == 1)
    for i, j in zip(obstacles[0], obstacles[1]):

        # calculate all cells in the radius
        for x in range(max(0, i - radius), min(len(grid), i + radius + 1)):
            for y in range(max(0, j - radius), min(len(grid[i]), j + radius + 1)):
                padded_grid[x][y] = 1

    return padded_grid


def get_neighbors(position, grid):
    neighbors = []
    i, j = position
    if i > 0 and grid[i - 1][j] != 1:
        neighbors.append((i - 1, j))
    if i < len(grid) - 1 and grid[i + 1][j] != 1:
        neighbors.append((i + 1, j))
    if j > 0 and grid[i][j - 1] != 1:
        neighbors.append((i, j - 1))
    if j < len(grid[i]) - 1 and grid[i][j + 1] != 1:
        neighbors.append((i, j + 1))
    return neighbors


def get_diagonal_neighbors(position, grid):
    neighbors = []
    i, j = position
    if i > 0 and j > 0 and grid[i - 1][j - 1] != 1:
        neighbors.append((i - 1, j - 1))
    if i < len(grid) - 1 and j < len(grid[i]) - 1 and grid[i + 1][j + 1] != 1:
        neighbors.append((i + 1, j + 1))
    if i > 0 and j < len(grid[i]) - 1 and grid[i - 1][j + 1] != 1:
        neighbors.append((i - 1, j + 1))
    if i < len(grid) - 1 and j > 0 and grid[i + 1][j - 1] != 1:
        neighbors.append((i + 1, j - 1))
    return neighbors


def djikstra(grid,start1,end1):
    print("start1",start1)
    print("end1:",end1)
    heap_queue = []
    distances = {}
    previous_elements = {}
    starting_position = np.where(grid == start1)
    print("Starting Pos:",starting_position)
    starting_position = (starting_position[0][0], starting_position[1][0])
    ending_position = np.where(grid == end1)
    print("Ending pos:",ending_position)
    ending_position = (ending_position[0][0], ending_position[1][0])
    
    
    

    for i in range(len(grid)):
        for j in range(len(grid[i])):
            
            if grid[i][j] == start1:
                heap_queue.append((0, (i, j)))
                distances[(i, j)] = 0
                previous_elements[(i, j)] = starting_position
            else:
                heap_queue.append((np.inf, (i, j)))
                distances[(i, j)] = np.inf
                previous_elements[(i, j)] = None

    while heap_queue:
        current_distance, current_position = heap_queue.pop(0)
        if current_position == ending_position:
            path = []
            while current_position != starting_position:
                path.append(current_position)
                current_position = previous_elements[current_position]
            path.append(starting_position)
            path.reverse()
            return path

        neighbors = get_neighbors(current_position, grid)
        diagonal_neighbors = get_diagonal_neighbors(current_position, grid)

        for neighbor in neighbors:
            distance = current_distance + 1
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                previous_elements[neighbor] = current_position

                # delete element from heap_queue
                for i in range(len(heap_queue)):
                    if heap_queue[i][1] == neighbor:
                        del heap_queue[i]
                        break

                heap_queue.append((distance, neighbor))
                heap_queue.sort()

        for neighbor in diagonal_neighbors:
            distance = current_distance + np.sqrt(2)
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                previous_elements[neighbor] = current_position

                # delete element from heap_queue
                for i in range(len(heap_queue)):
                    if heap_queue[i][1] == neighbor:
                        del heap_queue[i]
                        break

                heap_queue.append((distance, neighbor))
                heap_queue.sort()


def interpolate_path(points, num_points=1000, bc_type="natural"):

    points = np.array(points)
    x = points[:, 0]
    y = points[:, 1]

    # Parameterize by cumulative arc-length to handle non-monotonic x-values.
    distances = np.sqrt(np.diff(x) ** 2 + np.diff(y) ** 2)
    t = np.concatenate(([0], np.cumsum(distances)))

    # Fit cubic splines for x(t) and y(t)
    cs_x = CubicSpline(t, x, bc_type=bc_type)
    cs_y = CubicSpline(t, y, bc_type=bc_type)

    # Create a fine parameter grid for a smooth path
    t_fine = np.linspace(t[0], t[-1], num_points)
    x_fine = cs_x(t_fine)
    y_fine = cs_y(t_fine)

    return np.stack([x_fine, y_fine], axis=-1)


def get_path(grid,start1,end1, upscaling_factor=4, num_points=250, additional_obstacles = [], starting_pos_blocks = None):
    starting_grid = grid
    upscale_factor = upscaling_factor * 2 - 1  # ensure odd number

    for (obs_x, obs_y) in additional_obstacles:
        print("Assigning", obs_x, obs_y)
        if obs_x < 0 or obs_y < 0:
            continue
        if obs_x > len(starting_grid) or obs_y > len(starting_grid[0]):
            continue
            
        x_index = int(obs_x * upscale_factor + upscale_factor // 2)
        y_index = int(obs_y * upscale_factor + upscale_factor // 2)

        print("Assigning", x_index, y_index)
        starting_grid[x_index, y_index] = 1

    if starting_pos_blocks is not None:
        # remove all STARTING_POSITION_NUMBER from padded_grid
        for i in range(len(starting_grid)):
            for j in range(len(starting_grid[i])):
                if starting_grid[i][j] == STARTING_POSITION_NUMBER:
                    starting_grid[i][j] = 0

        start_x = starting_pos_blocks[0]
        start_y = starting_pos_blocks[1]
        
        # set starting position to 2
        starting_grid[int(start_x), int(start_y)] = 2


    upscaled_grid = np.zeros(
        (len(starting_grid) * upscale_factor, len(starting_grid[0]) * upscale_factor)
    )

    grid_to_print = ""
    for row in starting_grid:
        grid_to_print += ",".join(map(str, row)) + "\n"

    print(grid_to_print)

    for x, row in enumerate(starting_grid):
        for y, cell in enumerate(row):
            if not cell in [start1, end1]:
                upscaled_grid[x * upscale_factor : x * upscale_factor + upscale_factor, y * upscale_factor : y * upscale_factor + upscale_factor] = cell

    for x, row in enumerate(starting_grid):
        for y, cell in enumerate(row):
            if cell in [start1, end1]:
                upscaled_grid[x * upscale_factor + upscale_factor // 2, y * upscale_factor + upscale_factor // 2] = cell

    padded_grid = get_padded_grid(upscaled_grid, radius=max(upscale_factor - 1, 1))

    grid_to_print = ""
    for row in padded_grid:
        grid_to_print += ",".join(map(str, row)) + "\n"

    print(grid_to_print)
    
    path = djikstra(padded_grid,start1,end1)

    path = np.array(path)
    path = (path - (upscaling_factor - 1)) / upscale_factor

    interpolated_path = interpolate_path(path, num_points=num_points)

    return interpolated_path
